export enum PlotMakType {
  area = 'area',
  cell = 'cell',
  image = 'image',
  interval = 'interval',
  line = 'line',
  path = 'path',
  polygon = 'polygon',
  rectX = 'rectX',
  rectY = 'rectY',
  rect = 'rect',
  ruleX = 'ruleX',
  ruleY = 'ruleY',
  rule = 'rule',
  symbol = 'symbol',
  text = 'text',

  tree = 'tree',
  circlePacking = 'circlePacking',
  sunburst = 'sunburst',
  treemap = 'treemap',
  sankey = 'sankey',
  wordcloud = 'wordcloud',
  wordcloudShape = 'wordcloudShape',
  imagecloud = 'imagecloud'
}
