export const VGRAMMAR_VENN_DATUM_KEY = 'VGRAMMAR_VENN_DATUM_KEY';
export const VGRAMMAR_VENN_DATUM_TYPE = 'VGRAMMAR_VENN_DATUM_TYPE';
export const VGRAMMAR_VENN_LABEL_X = 'VGRAMMAR_VENN_LABEL_X';
export const VGRAMMAR_VENN_LABEL_Y = 'VGRAMMAR_VENN_LABEL_Y';
export const VGRAMMAR_VENN_CIRCLE_X = 'VGRAMMAR_VENN_CIRCLE_X';
export const VGRAMMAR_VENN_CIRCLE_Y = 'VGRAMMAR_VENN_CIRCLE_Y';
export const VGRAMMAR_VENN_CIRCLE_RADIUS = 'VGRAMMAR_VENN_CIRCLE_RADIUS';
export const VGRAMMAR_VENN_OVERLAP_PATH = 'VGRAMMAR_VENN_OVERLAP_PATH';
