import {
  View,
  // grammar,
  registerScale,
  registerCoordinate,
  // semantic mark
  registerCellMark,
  registerIntervalMark,
  registerGlyphMark,
  // components
  registerAxis,
  registerLegend,
  registerSlider,
  registerLabel,
  registerDataZoom,
  registerPlayer,
  registerTitle,
  registerGrid,
  registerScrollbar,
  // animations
  registerAnimate,
  registerViewMorphAPI,
  registerClipInAnimation,
  registerClipOutAnimation,
  registerFadeInAnimation,
  registerFadeOutAnimation,
  registerGrowAngleInAnimation,
  registerGrowAngleOutAnimation,
  registerGrowCenterInAnimation,
  registerGrowCenterOutAnimation,
  registerGrowHeightInAnimation,
  registerGrowHeightOutAnimation,
  registerGrowIntervalInAnimation,
  registerGrowIntervalOutAnimation,
  registerGrowPointsInAnimation,
  registerGrowPointsOutAnimation,
  registerGrowPointsXInAnimation,
  registerGrowPointsXOutAnimation,
  registerGrowPointsYInAnimation,
  registerGrowPointsYOutAnimation,
  registerGrowRadiusInAnimation,
  registerGrowRadiusOutAnimation,
  registerGrowWidthInAnimation,
  registerGrowWidthOutAnimation,
  registerMoveInAnimation,
  registerMoveOutAnimation,
  registerRotateInAnimation,
  registerRotateOutAnimation,
  registerScaleInAnimation,
  registerScaleOutAnimation,
  registerUpdateAnimation,
  // transforms
  registerBinTransform,
  registerContourTransform,
  registerSortTransform,
  registerFilterTransform,
  registerJoinTransform,
  registerKdeTransform,
  registerMapTransform,
  registerPickTransform,
  registerRangeTransform,
  registerStackTransform,
  registerFunnelTransform,
  registerPieTransform,
  registerCircularRelationTransform,
  registerFoldTransform,
  registerUnfoldTransform,
  registerIdentifierTransform,
  registerSampleTransform,
  registerMarkOverlapTransform,
  registerDodgeTransform,
  registerJitterTransform,
  registerJitterXTransform,
  registerJitterYTransform,
  registerSymmetryTransform,
  initAutoEnv,

  // interactions + animations
  registerViewEventsAPI,
  registerElementActive,
  registerElementSelect,
  registerElementHighlight,
  registerElementHighlightByKey,
  registerElementHighlightByGroup,
  registerElementActiveByLegend,
  registerElementHighlightByLegend,
  registerElementHighlightByName,
  registerBrushHighlight,
  registerBrushActive,
  registerBrushFilter,
  registerDrillDown,
  registerRollUp,
  registerTooltip,
  registerDimensionTooltip,
  registerCrosshair,
  registerViewZoom,
  registerViewScroll,
  registerViewDrag,
  registerViewRoam,
  registerFishEye,

  // graphics
  registerCircleGraphic,
  registerArcGraphic,
  registerArc3dGraphic,
  registerPyramid3dGraphic,
  registerAreaGraphic,
  registerGroupGraphic,
  registerImageGraphic,
  registerRect3dGraphic,
  registerLineGraphic,
  registerPathGraphic,
  registerRectGraphic,
  registerRuleGraphic,
  registerShapeGraphic,
  registerSymbolGraphic,
  registerTextGraphic,
  registerPolygonGraphic,
  registerRichTextGraphic,
  registerCellGraphic,
  registerIntervalGraphic,
  registerGlyphGraphic,
  registerLargeRectsGraphic,
  registerLargeSymbolsGraphic,

  // layout
  registerDefaultLayout
} from '@visactor/vgrammar-core';

View.useRegisters([
  registerDefaultLayout,
  // grammars
  registerScale,
  registerCoordinate,
  // marks
  registerCellMark,
  registerIntervalMark,
  registerGlyphMark,
  // components
  registerAxis,
  registerLegend,
  registerSlider,
  registerLabel,
  registerDataZoom,
  registerPlayer,
  registerTitle,
  registerGrid,
  registerScrollbar,

  // transforms
  registerBinTransform,
  registerContourTransform,
  registerSortTransform,
  registerFilterTransform,
  registerJoinTransform,
  registerKdeTransform,
  registerMapTransform,
  registerPickTransform,
  registerRangeTransform,
  registerStackTransform,
  registerFunnelTransform,
  registerPieTransform,
  registerCircularRelationTransform,
  registerFoldTransform,
  registerUnfoldTransform,
  registerIdentifierTransform,
  registerSampleTransform,
  registerMarkOverlapTransform,
  registerDodgeTransform,
  registerJitterTransform,
  registerJitterXTransform,
  registerJitterYTransform,
  registerSymmetryTransform,

  // animations
  registerAnimate,
  registerViewMorphAPI,
  registerClipInAnimation,
  registerClipOutAnimation,
  registerFadeInAnimation,
  registerFadeOutAnimation,
  registerGrowAngleInAnimation,
  registerGrowAngleOutAnimation,
  registerGrowCenterInAnimation,
  registerGrowCenterOutAnimation,
  registerGrowHeightInAnimation,
  registerGrowHeightOutAnimation,
  registerGrowIntervalInAnimation,
  registerGrowIntervalOutAnimation,
  registerGrowPointsInAnimation,
  registerGrowPointsOutAnimation,
  registerGrowPointsXInAnimation,
  registerGrowPointsXOutAnimation,
  registerGrowPointsYInAnimation,
  registerGrowPointsYOutAnimation,
  registerGrowRadiusInAnimation,
  registerGrowRadiusOutAnimation,
  registerGrowWidthInAnimation,
  registerGrowWidthOutAnimation,
  registerMoveInAnimation,
  registerMoveOutAnimation,
  registerRotateInAnimation,
  registerRotateOutAnimation,
  registerScaleInAnimation,
  registerScaleOutAnimation,
  registerUpdateAnimation,

  // interactions
  registerViewEventsAPI,
  registerElementActive,
  registerElementSelect,
  registerElementHighlight,
  registerElementHighlightByKey,
  registerElementHighlightByGroup,
  registerElementActiveByLegend,
  registerElementHighlightByLegend,
  registerElementHighlightByName,
  registerBrushHighlight,
  registerBrushActive,
  registerBrushFilter,
  registerDrillDown,
  registerRollUp,
  registerTooltip,
  registerDimensionTooltip,
  registerCrosshair,
  registerViewZoom,
  registerViewScroll,
  registerViewDrag,
  registerViewRoam,
  registerFishEye,

  // graphics
  registerCircleGraphic,
  registerArcGraphic,
  registerArc3dGraphic,
  registerPyramid3dGraphic,
  registerAreaGraphic,
  registerGroupGraphic,
  registerImageGraphic,
  registerRect3dGraphic,
  registerLineGraphic,
  registerPathGraphic,
  registerRectGraphic,
  registerRuleGraphic,
  registerShapeGraphic,
  registerSymbolGraphic,
  registerTextGraphic,
  registerPolygonGraphic,
  registerRichTextGraphic,
  registerCellGraphic,
  registerIntervalGraphic,
  registerGlyphGraphic,
  registerLargeRectsGraphic,
  registerLargeSymbolsGraphic
]);

initAutoEnv();

export * from '@visactor/vgrammar-core';
