import {
  View,
  // semantic mark
  registerCellMark,
  registerIntervalMark,
  // components
  registerAxis,
  registerLegend,
  registerSlider,
  registerLabel,
  registerDataZoom,
  registerPlayer,
  registerTitle,
  registerGrid,
  registerScrollbar,
  // animations
  registerClipInAnimation,
  registerClipOutAnimation,
  registerFadeInAnimation,
  registerFadeOutAnimation,
  registerGrowAngleInAnimation,
  registerGrowAngleOutAnimation,
  registerGrowCenterInAnimation,
  registerGrowCenterOutAnimation,
  registerGrowHeightInAnimation,
  registerGrowHeightOutAnimation,
  registerGrowIntervalInAnimation,
  registerGrowIntervalOutAnimation,
  registerGrowPointsInAnimation,
  registerGrowPointsOutAnimation,
  registerGrowPointsXInAnimation,
  registerGrowPointsXOutAnimation,
  registerGrowPointsYInAnimation,
  registerGrowPointsYOutAnimation,
  registerGrowRadiusInAnimation,
  registerGrowRadiusOutAnimation,
  registerGrowWidthInAnimation,
  registerGrowWidthOutAnimation,
  registerMoveInAnimation,
  registerMoveOutAnimation,
  registerRotateInAnimation,
  registerRotateOutAnimation,
  registerScaleInAnimation,
  registerScaleOutAnimation,
  registerUpdateAnimation,
  // transforms
  registerBinTransform,
  registerContourTransform,
  registerSortTransform,
  registerFilterTransform,
  registerJoinTransform,
  registerKdeTransform,
  registerMapTransform,
  registerPickTransform,
  registerRangeTransform,
  registerStackTransform,
  registerFunnelTransform,
  registerPieTransform,
  registerCircularRelationTransform,
  registerFoldTransform,
  registerUnfoldTransform,
  registerIdentifierTransform,
  registerSampleTransform,
  registerMarkOverlapTransform,
  registerDodgeTransform,
  registerJitterTransform,
  registerJitterXTransform,
  registerJitterYTransform,
  registerSymmetryTransform,
  initAllEnv,

  // interactions
  registerElementActive,
  registerElementSelect,
  registerElementHighlight,
  registerElementHighlightByKey,
  registerElementHighlightByGroup,
  registerElementActiveByLegend,
  registerElementHighlightByLegend,
  registerElementHighlightByName,
  registerBrushHighlight,
  registerBrushActive,
  registerBrushFilter,
  registerDrillDown,
  registerRollUp,
  registerTooltip,
  registerDimensionTooltip,
  registerCrosshair,
  registerViewZoom,
  registerViewScroll,
  registerViewDrag,
  registerViewRoam,
  registerFishEye
} from '@visactor/vgrammar-core';

View.useRegisters([
  registerCellMark,
  registerIntervalMark,
  // components
  registerAxis,
  registerLegend,
  registerSlider,
  registerLabel,
  registerDataZoom,
  registerPlayer,
  registerTitle,
  registerGrid,
  registerScrollbar,

  // transforms
  registerBinTransform,
  registerContourTransform,
  registerSortTransform,
  registerFilterTransform,
  registerJoinTransform,
  registerKdeTransform,
  registerMapTransform,
  registerPickTransform,
  registerRangeTransform,
  registerStackTransform,
  registerFunnelTransform,
  registerPieTransform,
  registerCircularRelationTransform,
  registerFoldTransform,
  registerUnfoldTransform,
  registerIdentifierTransform,
  registerSampleTransform,
  registerMarkOverlapTransform,
  registerDodgeTransform,
  registerJitterTransform,
  registerJitterXTransform,
  registerJitterYTransform,
  registerSymmetryTransform,

  // animations
  registerClipInAnimation,
  registerClipOutAnimation,
  registerFadeInAnimation,
  registerFadeOutAnimation,
  registerGrowAngleInAnimation,
  registerGrowAngleOutAnimation,
  registerGrowCenterInAnimation,
  registerGrowCenterOutAnimation,
  registerGrowHeightInAnimation,
  registerGrowHeightOutAnimation,
  registerGrowIntervalInAnimation,
  registerGrowIntervalOutAnimation,
  registerGrowPointsInAnimation,
  registerGrowPointsOutAnimation,
  registerGrowPointsXInAnimation,
  registerGrowPointsXOutAnimation,
  registerGrowPointsYInAnimation,
  registerGrowPointsYOutAnimation,
  registerGrowRadiusInAnimation,
  registerGrowRadiusOutAnimation,
  registerGrowWidthInAnimation,
  registerGrowWidthOutAnimation,
  registerMoveInAnimation,
  registerMoveOutAnimation,
  registerRotateInAnimation,
  registerRotateOutAnimation,
  registerScaleInAnimation,
  registerScaleOutAnimation,
  registerUpdateAnimation,

  // interactions
  registerElementActive,
  registerElementSelect,
  registerElementHighlight,
  registerElementHighlightByKey,
  registerElementHighlightByGroup,
  registerElementActiveByLegend,
  registerElementHighlightByLegend,
  registerElementHighlightByName,
  registerBrushHighlight,
  registerBrushActive,
  registerBrushFilter,
  registerDrillDown,
  registerRollUp,
  registerTooltip,
  registerDimensionTooltip,
  registerCrosshair,
  registerViewZoom,
  registerViewScroll,
  registerViewDrag,
  registerViewRoam,
  registerFishEye
]);

initAllEnv();

export * from '@visactor/vgrammar-core';
