name: Sync develop to main after release

on:
  pull_request:
    types:
      - closed
    branches:
      - 'release/[0-9]+.[0-9]+.[0-9]+'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: package-version
        uses: xile611/read-package-version-action@main
        with:
          path: packages/vgrammar

      - name: Create Pull Request
        uses: dustinirving/create-pr@v1.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: '[Auto merge] synchronize branch main to develop after release ${{ steps.package-version.outputs.current_version }}'
          base: develop
          head: main
          labels: release # default labels, the action will throw error if not specified
          reviewers: xile611 # default reviewers, the action will throw error if not specified
          body: |
            synchronize branch main to develop
