name: Sync develop to main after release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  if_merged:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './common/config/rush/pnpm-lock.yaml'

        # Install rush
      - name: Install rush
        run: node common/scripts/install-run-rush.js install --bypass-policy

      - name: Get version
        id: package-version
        uses: xile611/read-package-version-action@main
        with:
          path: packages/vgrammar

      - name: Rebase develop with main
        run: |
          git status
          git fetch origin develop:develop
          git checkout develop
          git fetch origin main
          git rebase origin/main
          git checkout -b 'sync-${{ steps.package-version.outputs.current_version }}-to-develop'
          git push origin 'sync-${{ steps.package-version.outputs.current_version }}-to-develop'

      - name: Create Pull Request
        uses: dustinirving/create-pr@v1.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: '[Auto merge] synchronize branch main to develop after release ${{ steps.package-version.outputs.current_version }}'
          base: develop
          head: 'sync-${{ steps.package-version.outputs.current_version }}-to-develop'
          labels: release # default labels, the action will throw error if not specified
          reviewers: xile611 # default reviewers, the action will throw error if not specified
          body: |
            synchronize branch main to develop
